### ISSUE TITLE
Add support to selectively hide page from the side menu

### ISSUE THREAD

**Issue by mgdesign** [sparkfabrik/company-playbook#195]
Raneto by default builds the side menu listing all the pages inside the content folder, organizing the menu items following the content folder structure. This causes some problems:
1) when the number of pages grows it becomes difficult to spor relevant pages on the menu
2) when the number of pages grows the menu is difficult to manage from a UI perspective
3) since the pages are sub-sections that are only relevant to the navigation coming from their parent

Raneto already provides the possibility to hide a page from the home,  using the flag `ShowOnHome` in the page metadata.

Using the same approach, we want to be able to hide a page from the sidebar if needed.

**Comment by stickgrinder** [comment]
Merged, great work!
