### ISSUE TITLE
Fix Docker and node_modules setup with entrypoint script

### ISSUE THREAD

**Issue by ailequal** [sparkfabrik/company-playbook#209]
After cloning the repository from scratch, I noticed that simply running `make` won't keep the new container up and running, due to an empty `./custom/node_modules` folder. Right now this is fixable by running `make cli` and then `npm install`.

The problem is related to the way Docker behaves and how mounted volumes work. Basically the dependencies are correctly installed on the container, but as soon as the mounting rules are applied, specifically this line `./custom/node_modules:/opt/raneto/node_modules`, then the entire folder in the container is wiped, since Docker gives priority to the files on the host system. The cleanest solution to this problem would be to setup up an entrypoint bash script, which is executed by Docker exactly after the mounting rules (this means moving the installation of the dependencies at the end of the process).

Also, there is another node_modules folder under `./custom/themes/spark-playbook/node_modules` which has the exact same problem, but right now for this specific one there is already a "fix", which is running outside from the Makefile `npm install` every time.

I am no expert regarding Docker, but I am pretty confident about my analysis, now I'd like to ask some feedback and support for implement these fixes.

**Comment by paolomainardi** [comment]
Thanks @ailequal, the analysis is right and you can take inspiration from here: https://github.com/paolomainardi/docker-backstage-devcontainers/tree/main/build/node

By implementing the entrypoint as you have thought.

**Comment by ailequal** [comment]
Closed, see pull #211.
