### ISSUE TITLE
Make ISC printable for rating sessions

### ISSUE THREAD

**Issue by stickgrinder** [sparkfabrik/company-playbook#24]
It would be great if, printing ISCs directly from the browser, tick-boxes for ratings appear as needed.
This would prevent having a "GDocs version" of the same ISCs to be maintained and kept in sync every time something changes.

Any idea?

**Comment by mgdesign** [comment]
`@media print` css it's quite an interesting theme, and a vast one.

Here are some suggestions and things to consider:
https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/

Especially page-breaking could be something to put some attention on. Everything concerning the styling itself (icons, etc) it's almost basic css.

**Comment by francescoben** [comment]
@stickgrinder it only took a year :smile:
